DROP DATABASE IF EXISTS `shvatka`;
CREATE DATABASE `shvatka` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

DROP DATABASE IF EXISTS `shvatka_tests`;
CREATE SCHEMA `shvatka_tests` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;